# Site settings
course_name: Statistical Learning and Data Mining
course_description: "Statistical learning refers to a set of tools for modeling and understanding complex datasets. It is a recently developed area in statistics and blends with parallel developments in computer science and, in particular, machine learning. We will cover how to use machine learning techniques and statistics with the goal of statistical inference: drawing conclusions on the data at hand. This course encompasses many methods such as regression, classification, regression trees, boosting, support vector machines, clustering and dimension reduction."
course_semester: "Fall 2022"

baseurl: "/nsysu-math524-2022/" # the subpath of your site, e.g. /blog/
url: "https://phonchi.github.io/" # the base hostname & protocol for your site

schoolname: "National Sun Yat-Sen University"
schoolurl: "https://www.nsysu.edu.tw/"
#twitter_username: username 

address: |
    No.70 Lien-hai Rd., Kaohsiung 80424, 
    Taiwan

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"

